version: '3'

tasks:
  start:
    desc: Start all services (builds images if needed)
    cmds:
      - docker compose up -d --build

  stop:
    desc: Stop all services
    cmds:
      - docker compose down

  run:
    desc: Run the agent main function
    cmds:
      - docker compose exec jupyter python -m homework.agent

  test:
    desc: Run the agent tests
    cmds:
      - docker compose exec jupyter pytest homework_test/agent_test.py --log-cli-level=INFO
